// Fizzbuzz implementation by someone who loves C but hates semicolon 
// Le Python Lovers : We don't need semicolon , Le C Lovers : Read my code 
// Author : @Trimankaur

#include<stdio.h> 
int main() 
{ 
if (printf("1\n")){}
if (printf("2\n")){}
if (printf("Fizz\n")){}
if (printf("4\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("7\n")){}
if (printf("8\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
if (printf("11\n")){}
if (printf("Fizz\n")){}
if (printf("13\n")){}
if (printf("14\n")){}
if (printf("FizzBuzz\n")){}
if (printf("16\n")){}
if (printf("17\n")){}
if (printf("Fizz\n")){}
if (printf("19\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("22\n")){}
if (printf("23\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
if (printf("26\n")){}
if (printf("Fizz\n")){}
if (printf("28\n")){}
if (printf("29\n")){}
if (printf("FizzBuzz\n")){}
if (printf("31\n")){}
if (printf("32\n")){}
if (printf("Fizz\n")){}
if (printf("34\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("37\n")){}
if (printf("38\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
if (printf("41\n")){}
if (printf("Fizz\n")){}
if (printf("43\n")){}
if (printf("44\n")){}
if (printf("FizzBuzz\n")){}
if (printf("46\n")){}
if (printf("47\n")){}
if (printf("Fizz\n")){}
if (printf("49\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("52\n")){}
if (printf("53\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
if (printf("56\n")){}
if (printf("Fizz\n")){}
if (printf("58\n")){}
if (printf("59\n")){}
if (printf("FizzBuzz\n")){}
if (printf("61\n")){}
if (printf("62\n")){}
if (printf("Fizz\n")){}
if (printf("64\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("67\n")){}
if (printf("68\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
if (printf("71\n")){}
if (printf("Fizz\n")){}
if (printf("73\n")){}
if (printf("74\n")){}
if (printf("FizzBuzz\n")){}
if (printf("76\n")){}
if (printf("77\n")){}
if (printf("Fizz\n")){}
if (printf("79\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("82\n")){}
if (printf("83\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
if (printf("86\n")){}
if (printf("Fizz\n")){}
if (printf("88\n")){}
if (printf("89\n")){}
if (printf("FizzBuzz\n")){}
if (printf("91\n")){}
if (printf("92\n")){}
if (printf("Fizz\n")){}
if (printf("94\n")){}
if (printf("Buzz\n")){}
if (printf("Fizz\n")){}
if (printf("97\n")){}
if (printf("98\n")){}
if (printf("Fizz\n")){}
if (printf("Buzz\n")){}
} 
